### ISSUE TITLE
AndroidCommon.robot

### ISSUE THREAD

**Issue by TGPSeventh** [LambdaTest/LT-appium-python-robot#8]
I got a question to where did the variables in the temp file came from?
It has no declaration I think.

I am new to LambdaTest thank you for your help.

![image](https://user-images.githubusercontent.com/118314938/211504495-e7059938-eba7-4e33-8caa-22e4cbe51ddc.png)

**Comment by aakashv145** [comment]
Value for Capabilities defined in @{_temp} are fetched from Make file command used for test execution.
```
@{_tmp}   
    ...   platformName: ${platformName}
    ...   platformVersion: ${version}
    ...   deviceName: ${deviceName}
    ...   visual: ${visual}
    ...   network: ${network}
    ...   isRealMobile: ${isRealMobile}
    ...   name: 'RobotFramework Lambda Test'
    ...   app: 'lt://proverbial-ios'

```
Command used for Test Execution from Make File
`robot  --variable platformName:Android --variable version:10 --variable deviceName:"Galaxy S20" --variable visual:false --variable network:false --variable isRealMobile:true  Tests/Android.robot
`
NOTE : Capability value can be both defined in @{_temp} or can be fetched from Make File Command.

Common Robot File where capabilities were defined- [(https://github.com/LambdaTest/LT-appium-python-robot/blob/master/Resources/Common.robot)](url)
Make File- [ https://github.com/LambdaTest/LT-appium-python-robot/blob/master/Makefile](url)
