### ISSUE TITLE
Scrolling to a Specific Element in Native iOS Automation is not working 

### ISSUE THREAD

**Issue by devlove1C** [LambdaTest/LT-appium-python-robot#9]
Hi Team,
We are currently utilizing the Robot Framework to create automation scripts for native iOS applications. Throughout the automation process, we have been relying on **accessibility IDs** to interact with elements within the application. However, I have encountered challenges when attempting to scroll to a particular element. The built-in scroll commands (**scroll, scroll up, and scroll down**) provided by the Robot Framework scroll the application screen but sometimes bypass the specific element I need to interact with. Instead, they move further up or down, missing the target element.

Used version
iOS version - 15
Appium Version - 2.0.0

I would greatly appreciate your assistance in resolving this issue and finding an effective way to scroll the screen until the desired element is in view. 
Thank you for your help

**Comment by aakashv145** [comment]
In Robot Framework Scrolling Actions can be performed using mentioned pre-defined keywords:
- Scroll
- Scroll Up
- Scroll Down
- Scroll Element Into View

However, Scroll Element into View will scroll down to desired element locator until the element is visible on the Web UI

Syntax: `Scroll Element Into View          locator `

After performing Scrolling Action, we can validate the presence of desired element locator.

Link for keyword reference- [https://serhatbolsu.github.io/robotframework-appiumlibrary/AppiumLibrary.html#Scroll%20Element%20Into%20View](url)
